# Generated by Django 3.0.6 on 2020-05-09 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200509_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='space',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Space'),
        ),
    ]
