# Generated by Django 3.0.6 on 2020-05-09 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20200509_1132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='space',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.Space'),
            preserve_default=False,
        ),
    ]
