# Generated by Django 3.0.6 on 2020-05-12 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20200512_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='space',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
