# Generated by Django 3.0.6 on 2020-05-13 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20200512_1518'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='user',
            new_name='userID',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='space',
            new_name='spaceID',
        ),
        migrations.AlterUniqueTogether(
            name='user',
            unique_together={('spaceID', 'name')},
        ),
    ]
