# Generated by Django 3.0.6 on 2020-05-13 20:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20200513_1515'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='spaceID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.Space'),
            preserve_default=False,
        ),
    ]
