# Generated by Django 3.0.6 on 2020-05-14 00:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20200513_1956'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='space',
        ),
    ]
