# Generated by Django 3.0.6 on 2020-05-26 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_response'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requesttype',
            name='name',
            field=models.CharField(max_length=15, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='response',
            unique_together={('request', 'user')},
        ),
    ]
