# Generated by Django 3.0.6 on 2020-05-26 00:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    atomic = False

    dependencies = [
        ('app', '0018_auto_20200525_2003'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpaceResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.BooleanField()),
                ('timestamp', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='RequestType',
            new_name='SpaceRequestType',
        ),
        migrations.RenameModel(
            old_name='Request',
            new_name='SpaceRequest',
        ),
        migrations.DeleteModel(
            name='Response',
        ),
        migrations.AddField(
            model_name='spaceresponse',
            name='spaceRequest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.SpaceRequest'),
        ),
        migrations.AddField(
            model_name='spaceresponse',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.User'),
        ),
        migrations.AlterUniqueTogether(
            name='spaceresponse',
            unique_together={('spaceRequest', 'user')},
        ),
    ]
