# Generated by Django 3.0.6 on 2020-05-26 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_poll_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='space',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Space'),
        ),
    ]
