# Generated by Django 3.0.6 on 2020-05-27 19:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_auto_20200527_1128'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreatePoll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('status', models.NullBooleanField()),
                ('timestamp', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CreateVote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('result', models.BooleanField()),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('createPoll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.CreatePoll')),
            ],
        ),
        migrations.RemoveField(
            model_name='vote',
            name='poll',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='user',
        ),
        migrations.DeleteModel(
            name='Poll',
        ),
        migrations.DeleteModel(
            name='PollType',
        ),
        migrations.DeleteModel(
            name='Vote',
        ),
    ]
