# Generated by Django 3.0.6 on 2020-05-28 02:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_auto_20200527_1956'),
    ]

    operations = [
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.NullBooleanField()),
                ('name', models.CharField(max_length=50)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Space')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.User')),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.BooleanField()),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Poll')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.User')),
            ],
            options={
                'unique_together': {('poll', 'user')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='createvote',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='createvote',
            name='createPoll',
        ),
        migrations.DeleteModel(
            name='CreatePoll',
        ),
        migrations.DeleteModel(
            name='CreateVote',
        ),
    ]
